CREATE TABLE users(
    uid INT NOT NULL AUTO_INCREMENT,
    uname VARCHAR(60) UNIQUE NOT NULL,
    uemail VARCHAR(100) NOT NULL,
    upassword VARCHAR(500) NOT NULL,
    uprofileimg MEDIUMBLOB,
    uprofileimgtype VARCHAR(10),
    PRIMARY KEY(uid)
) ENGINE=InnoDB;

CREATE TABLE images(
    iname VARCHAR(60) NOT NULL,
    uid INT NOT NULL,
    PRIMARY KEY(iname),
    FOREIGN KEY(uid) REFERENCES users(uid)
    ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB;